name = "Scorio"
uuid = "8b85e2e0-9a7f-4d8f-8e1e-3c5c7d5e8e0a"
authors = ["Mohsen Hariri <mohsen.hariri@case.edu>"]
version = "0.2.0"

[deps]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
HiGHS = "1"
JuMP = "1"
NPZ = "0.4"
julia = "1.6"

[extras]
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "NPZ"]
